#!/usr/bin/env python3
"""Render ADR YAML files to Markdown documents.

Usage:
    python3 scripts/render-adr.py examples-reference/fictional/ADR-0001-*.yaml
    python3 scripts/render-adr.py examples-reference/fictional/       # render all fictional examples
    python3 scripts/render-adr.py --output-dir architecture-decision-log/rendered/ --generate-index architecture-decision-log/
"""

import argparse
import os
import sys

import yaml


def render_disclaimer(source_yaml_relpath: str) -> str:
    """Render the auto-generated disclaimer banner.

    Produces both an HTML comment (machine-detectable provenance) and a
    GitHub / Azure DevOps alert block that renders visually.
    """
    basename = os.path.basename(source_yaml_relpath)
    return "\n".join([
        "<!-- ⚠️ AUTO-GENERATED — DO NOT EDIT -->",
        f"<!-- Source of truth: {source_yaml_relpath} -->",
        "",
        "> [!CAUTION]",
        f"> **This file is auto-generated** from [`{basename}`]({source_yaml_relpath}).",
        "> Do not edit this file directly — all changes must be made in the YAML source.",
        "",
        "",
    ])


def table_cell(value: str) -> str:
    """Collapse newlines and normalize whitespace for Markdown table cells.

    GitHub's Markdown parser treats newlines inside table rows as row
    terminators, breaking the table layout.  This helper folds multiline
    YAML scalars into a single line suitable for a table cell.
    """
    return " ".join(str(value).split())


def render_adr(data: dict) -> str:
    """Render a parsed ADR YAML dict to a Markdown string."""
    lines = []

    adr = data.get("adr", {})
    title = adr.get("title", "Untitled")
    adr_id = adr.get("id", "ADR-????")

    # --- Header ---
    lines.append(f"# {adr_id}: {title}")
    lines.append("")

    # Metadata table
    status = adr.get("status", "unknown")
    priority = adr.get("priority", "—")
    decision_type = adr.get("decision_type", "—")
    confidence = data.get("decision", {}).get("confidence", "—")
    decision_date = data.get("decision", {}).get("decision_date", "—")
    owner = data.get("decision_owner", {})
    owner_str = f"{owner.get('name', '—')} ({owner.get('role', '')})" if owner else "—"

    # Trailing two spaces produce soft line breaks (new line, no paragraph gap)
    lines.append(f"> **Status:** `{status}`  ")
    lines.append(f"> **Priority:** `{priority}`  ")
    lines.append(f"> **Type:** `{decision_type}`  ")
    decision_level = adr.get("decision_level")
    if decision_level:
        lines.append(f"> **Level:** `{decision_level}`  ")
    lines.append(f"> **Confidence:** `{confidence}`  ")
    lines.append(f"> **Decision Owner:** {owner_str}  ")
    lines.append(f"> **Decision Date:** {decision_date}")
    lines.append("")

    # Y-Statement (Zimmermann/Fairbanks long form)
    if adr.get("y_statement"):
        lines.append(f"> *{adr['y_statement'].strip()}*")
        lines.append("")

    # --- Authors & Reviewers ---
    authors = data.get("authors", [])
    reviewers = data.get("reviewers", [])
    approvals = data.get("approvals", [])
    if authors or reviewers or approvals:
        lines.append("---")
        lines.append("")
        # Trailing two spaces for soft line breaks (compact, no paragraph gaps)
        parts = []
        if authors:
            parts.append(f"**Authors:** {', '.join(a.get('name', '') + ' (' + a.get('role', '') + ')' for a in authors)}")
        if reviewers:
            parts.append(f"**Reviewers:** {', '.join(r.get('name', '') + ' (' + r.get('role', '') + ')' for r in reviewers)}")
        if approvals:
            approval_parts = []
            for approval in approvals:
                name = approval.get("name", "")
                role = approval.get("role", "")
                identity = str(approval.get("identity", "")).strip()
                approved_at = approval.get("approved_at")

                label = name or "Unknown approver"
                if role:
                    label += f" ({role})"
                if identity:
                    label += f" [{identity}]"
                if approved_at:
                    label += f" — approved {approved_at}"
                else:
                    label += " — pending"
                approval_parts.append(label)

            if approval_parts:
                parts.append(f"**Approvals:** {'; '.join(approval_parts)}")
        for i, part in enumerate(parts):
            if i < len(parts) - 1:
                lines.append(part + "  ")  # soft break
            else:
                lines.append(part)
        lines.append("")

    # --- Context ---
    context = data.get("context", {})
    lines.append("---")
    lines.append("")
    lines.append("## Context")
    lines.append("")
    if context.get("description"):
        lines.append(context["description"].strip())
        lines.append("")

    for section_key, section_title in [("business_drivers", "Business Drivers"), ("technical_drivers", "Technical Drivers"),
                                        ("constraints", "Constraints"), ("assumptions", "Assumptions")]:
        items = context.get(section_key, [])
        if items:
            lines.append(f"### {section_title}")
            lines.append("")
            for item in items:
                lines.append(f"- {item}")
            lines.append("")

    # --- Architecturally Significant Requirements ---
    reqs = data.get("architecturally_significant_requirements", {})
    functional = reqs.get("functional", [])
    non_functional = reqs.get("non_functional", [])
    if functional or non_functional:
        lines.append("## Architecturally Significant Requirements")
        lines.append("")
        if functional:
            lines.append("### Functional")
            lines.append("")
            lines.append("| ID | Description |")
            lines.append("|----|-------------|")
            for r in functional:
                lines.append(f"| `{r.get('id', '')}` | {table_cell(r.get('description', ''))} |")
            lines.append("")
        if non_functional:
            lines.append("### Non-Functional")
            lines.append("")
            lines.append("| ID | Description |")
            lines.append("|----|-------------|")
            for r in non_functional:
                lines.append(f"| `{r.get('id', '')}` | {table_cell(r.get('description', ''))} |")
            lines.append("")

    # --- Alternatives ---
    alternatives = data.get("alternatives", [])
    if alternatives:
        lines.append("## Alternatives Considered")
        lines.append("")
        decision = data.get("decision", {})
        chosen = decision.get("chosen_alternative", "")

        for i, alt in enumerate(alternatives, 1):
            name = alt.get("name", f"Option {i}")
            is_chosen = name == chosen
            marker = " ✅" if is_chosen else ""
            lines.append(f"### {i}. {name}{marker}")
            lines.append("")
            if alt.get("description"):
                lines.append(alt["description"].strip())
                lines.append("")
            if alt.get("pros"):
                lines.append("**Pros:**")
                for p in alt["pros"]:
                    lines.append(f"- {p}")
                lines.append("")
            if alt.get("cons"):
                lines.append("**Cons:**")
                for c in alt["cons"]:
                    lines.append(f"- {c}")
                lines.append("")
            cost = alt.get("estimated_cost", "")
            risk = alt.get("risk", "")
            if cost or risk:
                lines.append(f"*Estimated cost: `{cost}` · Risk: `{risk}`*")
                lines.append("")
            if alt.get("rejection_rationale"):
                lines.append(f"> **Rejection rationale:** {alt['rejection_rationale'].strip()}")
                lines.append("")

    # --- Decision ---
    decision = data.get("decision", {})
    if decision:
        lines.append("## Decision")
        lines.append("")
        lines.append(f"**Chosen alternative:** {decision.get('chosen_alternative', '—')}")
        lines.append("")
        if decision.get("rationale"):
            lines.append("### Rationale")
            lines.append("")
            lines.append(decision["rationale"].strip())
            lines.append("")
        if decision.get("tradeoffs"):
            lines.append("### Tradeoffs")
            lines.append("")
            lines.append(decision["tradeoffs"].strip())
            lines.append("")

    # --- Consequences ---
    consequences = data.get("consequences", {})
    positive = consequences.get("positive", [])
    negative = consequences.get("negative", [])
    if positive or negative:
        lines.append("## Consequences")
        lines.append("")
        if positive:
            lines.append("### Positive")
            lines.append("")
            for item in positive:
                lines.append(f"- {item}")
            lines.append("")
        if negative:
            lines.append("### Negative")
            lines.append("")
            for item in negative:
                lines.append(f"- {item}")
            lines.append("")

    # --- Confirmation ---
    confirmation = data.get("confirmation", {})
    if confirmation:
        lines.append("## Confirmation")
        lines.append("")
        if confirmation.get("description"):
            lines.append(confirmation["description"].strip())
            lines.append("")
        if confirmation.get("artifact_ids"):
            lines.append("**Artifacts:**")
            for aid in confirmation["artifact_ids"]:
                if aid.startswith("http"):
                    lines.append(f"- [{aid}]({aid})")
                else:
                    lines.append(f"- `{aid}`")
            lines.append("")

    # --- Dependencies ---
    deps = data.get("dependencies", {})
    internal = deps.get("internal", [])
    external = deps.get("external", [])
    if internal or external:
        lines.append("## Dependencies")
        lines.append("")
        if internal:
            lines.append("**Internal:**")
            for d in internal:
                lines.append(f"- {d}")
            lines.append("")
        if external:
            lines.append("**External:**")
            for d in external:
                lines.append(f"- {d}")
            lines.append("")

    # --- References ---
    refs = data.get("references", [])
    if refs:
        lines.append("## References")
        lines.append("")
        for r in refs:
            title = r.get("title", "")
            url = r.get("url", "")
            lines.append(f"- [{title}]({url})")
        lines.append("")

    # --- Lifecycle ---
    lifecycle = data.get("lifecycle", {})
    if lifecycle:
        lines.append("## Lifecycle")
        lines.append("")
        review = lifecycle.get("review_cycle_months")
        next_review = lifecycle.get("next_review_date")
        sup_by = lifecycle.get("superseded_by")
        sup = lifecycle.get("supersedes")
        archival = lifecycle.get("archival", {})
        if review:
            lines.append(f"- **Review cycle:** {review} months")
        if next_review:
            lines.append(f"- **Next review:** {next_review}")
        if sup_by:
            lines.append(f"- **Superseded by:** {sup_by}")
        if sup:
            lines.append(f"- **Supersedes:** {sup}")
        if archival:
            archived_at = archival.get("archived_at")
            archive_reason = archival.get("archive_reason")
            if archived_at:
                lines.append(f"- **Archived at:** {archived_at}")
            if archive_reason:
                lines.append(f"- **Archive reason:** {archive_reason}")
        lines.append("")

    # --- Audit Trail ---
    audit_trail = data.get("audit_trail", [])
    if audit_trail:
        lines.append("## Audit Trail")
        lines.append("")
        lines.append("| Event | By | Date | Details |")
        lines.append("|-------|----|------|---------|")
        for e in audit_trail:
            event = e.get("event", "")
            by = e.get("by", "")
            at = str(e.get("at", ""))[:10]  # date portion only
            details = table_cell(e.get("details", ""))
            lines.append(f"| `{event}` | {by} | {at} | {details} |")
        lines.append("")

    # --- Custom Extensions (x- prefixed) ---
    extension_keys = sorted(k for k in data if k.startswith("x-"))
    if extension_keys:
        lines.append("## Custom Extensions")
        lines.append("")
        for key in extension_keys:
            value = data[key]
            if isinstance(value, str):
                lines.append(f"- **{key}:** {value}")
            elif isinstance(value, list):
                lines.append(f"**{key}:**")
                for item in value:
                    lines.append(f"- {item}")
            elif isinstance(value, dict):
                lines.append(f"**{key}:**")
                for k, v in value.items():
                    lines.append(f"- **{k}:** {v}")
            else:
                lines.append(f"- **{key}:** {value}")
        lines.append("")

    return "\n".join(lines)


def generate_index(entries: list) -> str:
    """Generate the Architecture Decision Log index Markdown.

    Produces a table with clickable links, status, and decision date.
    No enumeration — entries appear in natural ADR-ID order.
    """
    lines = [
        "<!-- ⚠️ AUTO-GENERATED — DO NOT EDIT -->",
        "<!-- Regenerate: python3 scripts/render-adr.py --output-dir architecture-decision-log/rendered/ --generate-index architecture-decision-log/ -->",
        "",
        "# Architecture Decision Log",
        "",
        "| ADR | Status | Decision Date | Source |",
        "|-----|--------|---------------|--------|",
    ]
    for entry in entries:
        adr_id = entry["id"]
        title = entry["title"]
        status = entry["status"]
        date = entry.get("decision_date", "—")
        md_file = entry["md_filename"]
        yaml_relpath = entry["yaml_relpath"]
        yaml_basename = os.path.basename(yaml_relpath)
        lines.append(
            f"| [{adr_id}: {title}](./{md_file}) "
            f"| `{status}` | {date} "
            f"| [{yaml_basename}]({yaml_relpath}) |"
        )
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Render ADR YAML files to Markdown")
    parser.add_argument("targets", nargs="+", help="YAML files or directories to render")
    parser.add_argument("--output-dir", "-o", help="Output directory (default: print to stdout)")
    parser.add_argument("--generate-index", action="store_true",
                        help="Generate an architecture-decision-log.md index file in output-dir")
    args = parser.parse_args()

    # Collect files
    files = []
    for target in args.targets:
        if os.path.isdir(target):
            for dirpath, _, filenames in os.walk(target):
                for f in filenames:
                    if f.endswith((".yaml", ".yml")):
                        files.append(os.path.join(dirpath, f))
        elif os.path.isfile(target):
            files.append(target)
        else:
            print(f"WARNING: {target} not found, skipping", file=sys.stderr)
    files.sort(key=lambda p: os.path.basename(p))

    if not files:
        print("No YAML files found.", file=sys.stderr)
        sys.exit(1)

    index_entries = []

    for filepath in files:
        with open(filepath, "r") as f:
            data = yaml.safe_load(f)

        if not isinstance(data, dict) or "adr" not in data:
            print(f"SKIP: {filepath} (not an ADR file)", file=sys.stderr)
            continue

        markdown = render_adr(data)

        if args.output_dir:
            os.makedirs(args.output_dir, exist_ok=True)
            basename = os.path.splitext(os.path.basename(filepath))[0] + ".md"
            output_path = os.path.join(args.output_dir, basename)

            # Compute relative path from output file back to source YAML
            source_yaml_relpath = os.path.relpath(filepath, args.output_dir)
            disclaimer = render_disclaimer(source_yaml_relpath)

            with open(output_path, "w") as f:
                f.write(disclaimer + markdown)
            print(f"  RENDERED: {filepath} → {output_path}")

            # Collect entry for the index
            adr = data.get("adr", {})
            decision = data.get("decision", {})
            index_entries.append({
                "id": adr.get("id", "ADR-????"),
                "title": adr.get("title", "Untitled"),
                "status": adr.get("status", "unknown"),
                "decision_date": str(decision.get("decision_date", "—")),
                "md_filename": basename,
                "yaml_relpath": source_yaml_relpath,
            })
        else:
            print(markdown)
            if len(files) > 1:
                print("\n" + "=" * 72 + "\n")

    # Generate index file
    if args.generate_index:
        if not args.output_dir:
            print("ERROR: --generate-index requires --output-dir", file=sys.stderr)
            sys.exit(1)
        index_path = os.path.join(args.output_dir, "architecture-decision-log.md")
        index_content = generate_index(index_entries)
        with open(index_path, "w") as f:
            f.write(index_content)
        print(f"  INDEX: {index_path} ({len(index_entries)} entries)")


if __name__ == "__main__":
    main()
